# Generated by Django 4.2.8 on 2024-04-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(default='')),
            ],
        ),
    ]
