# Generated by Django 4.2.8 on 2024-04-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_board_id_board_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='updated_at',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
